version: '3.8'
services:
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - '3306:5432'
    # express:
    #   image: nodejs:20.9.0
    #   command: bash -c "npm install && npm start"
    #   depends_on:
    #     - postgres
volumes:
    postgres:
